[theme]
primaryColor = "#FF2D2D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF0F0"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
